### ISSUE TITLE
Tutorial requirements

### ISSUE THREAD

**Issue by samodadela** [DKE-Data/agrirouter-api-developer-tutorial#22]
Please clarify: 
- Is the developer account required for all the steps in this tutorial? Or can a user account be used?
- Is there a way to evaluate the API without having to get a developer account?

What's not clear is that chapter 2 is titled "create developer account" but the video shows how to create a regular user account.

**Comment by saschadoemer** [comment]
Hey,

you need to create a developer account, but the developer account is free to create. There should be one developer account per company and the developer account has the same features as the enduser account.

https://docs.agrirouter.com/agrirouter-interface-documentation/latest/accounts.html

To register a developer account, please visit https://goto.my-agrirouter.com/ and register a new developer account:

![image](https://github.com/DKE-Data/agrirouter-api-developer-tutorial/assets/1309344/1ff650fc-7825-4d4a-9472-6159d25cb82e)

After registration the account will be approved by the DKE and you can start with the development. There is the possibility, that either @oliverrahner, @FelixLammers0110 or @capke may contact you for addtional information.

Does this answer your questions?

**Comment by samodadela** [comment]
@saschadoemer @oliverrahner et all - I have a few more questions. 

Which developer account do I need to create - QA or regular one? For starters I'd just test out the API (for example I'd like to listen to the messages from all tractors on the agrirouter and save the pictures to a folder).

I'm also confused about membership - on this agrirouter [page](https://agrirouter.com/en/company/association/)  it says that membership is free for farmers and contractors - does that mean that developers and QA must become members first?

**Comment by saschadoemer** [comment]
It would be best to create an account on production, regarding the membership @oliverrahner would be the better approach 👌🏻

**Comment by oliverrahner** [comment]
@samodadela All companies wanting to implement the agrirouter interface need to be members. The whole agrirouter initiative is aimed at improving connectivity for all players along the agricultural value chain, thus the cost for operating the platform is split between all members.
There is some yet-to-be-QA'd information available here: https://docs.agrirouter.com/_branches/pr/167/agrirouter-interface-documentation/latest/partner-process/legal-agreement.html
If you want to pursue this further, the best option would be to contact c.apke@dke-data.com, we would then set up an introductory call with you.

**Comment by samodadela** [comment]
@oliverrahner That sounds reasonable. Thanks for clarifying.
@saschadoemer You can close this, thanks.
